# Generated by Django 4.2 on 2023-05-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hobby',
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
