# Generated by Django 4.1.7 on 2023-06-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_hobby_profile_grade_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
