# Generated by Django 4.2.1 on 2023-06-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_profile_hobby_profile_grade_profile_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hates",
            field=models.ManyToManyField(related_name="haters", to="accounts.profile"),
        ),
        migrations.AddField(
            model_name="profile",
            name="likes",
            field=models.ManyToManyField(related_name="likers", to="accounts.profile"),
        ),
    ]
