# Generated by Django 4.1.7 on 2023-06-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='info',
            field=models.CharField(choices=[('pending', '팀플 생성자가 승인 여부를 결정하지 못했어요!!'), ('accepted', '승인'), ('rejected', '팀플 생성자가 승인을 거부했습니다.\n다른 팀플을 찾아보세요!!')], max_length=10),
        ),
    ]
