# Generated by Django 4.1.7 on 2023-06-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_testresult_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
