# Generated by Django 4.2.1 on 2023-06-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_post_describe"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="propensity",
            field=models.TextField(default="ㅋㅋ"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.TextField(default="ㅋㅋ"),
            preserve_default=False,
        ),
    ]
