# Generated by Django 4.2.1 on 2023-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_post_propensity_post_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="propensity",
            field=models.TextField(blank=True, null=True),
        ),
    ]
